" Quick and dirty vim config

"-- plugins
" run ':PlugInstall' to update

call plug#begin()

Plug 'sheerun/vim-polyglot'
Plug 'itchyny/lightline.vim'
Plug 'joshdick/onedark.vim'
Plug 'scrooloose/nerdtree'
Plug 'wincent/terminus'
Plug 'xuhdev/vim-latex-live-preview', { 'for': 'tex' }

call plug#end()

"-- basics

set number
set cursorline
set incsearch
set ruler
set nocompatible
set shiftwidth=4
set tabstop=4
set expandtab
set showmatch
set noshowmode

"-- bindings

nnoremap <C-up> <C-y>
nnoremap <C-k> <C-y>

nnoremap <C-down> <C-E>
nnoremap <C-j> <C-E>

map <C-n> :NERDTreeToggle<CR>

command Pdfrun execute "silent !pandoc --filter pandoc-citeproc -o %.pdf %" | redraw!
map <F5> :Pdfrun<CR>

vmap <C-c> :w !xclip -i -sel c

"-- colour

if (empty($TMUX))
  if (has("nvim"))
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  if (has("termguicolors"))
    set termguicolors
  endif
endif

let g:lightline = {
  \ 'colorscheme': 'onedark',
  \ }

syntax on
set laststatus=2
colorscheme onedark

"-- Latex
let g:livepreview_previewer = 'zathura'

